[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/news/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/community/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
